title: "Curriculum Vitae"
description: "Data Science needs solid direction. Too often, we're lead astray by the buzz and hype of Data Science. I'm here to make statistics wholesome again."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: GFM
