title: "Curriculum Vitae"
description: "Data Science needs solid direction.<br>Too often, we're lead astray by the buzz and hype of Data Science.<br>I'm here to make it _wholesome_ again."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: GFM
show_downloads: true

